import React from "react";
import { Link } from "react-router-dom";
import { FaGithub } from "react-icons/fa";
import { Database, Users, Lightbulb, Search, UserRound, Rocket, Code2, Sparkles, ArrowRight, Mail, Phone,  ChevronRight, Layers3, ShieldCheck, Zap, Compass } from "lucide-react";

const Home = () => (
  <div className="min-h-screen overflow-hidden bg-[#090b10] text-white">
    <section className="relative px-6 pb-24 pt-32 sm:px-10 lg:px-16">
      <div className="pointer-events-none absolute left-1/2 top-0 h-96 w-96 -translate-x-1/2 rounded-full bg-cyan-400/10 blur-[140px]" />
      <div className="pointer-events-none absolute right-0 top-40 h-80 w-80 rounded-full bg-violet-500/10 blur-[130px]" />
      <div className="relative mx-auto max-w-6xl text-center">
        <div className="mx-auto inline-flex items-center gap-2 rounded-full border border-cyan-400/10 bg-cyan-400/[0.04] px-4 py-2 text-xs font-medium tracking-wide text-cyan-300 animate-[fadeInUp_.6s_ease-out_both]"><Sparkles size={14}/>Build smarter. Discover faster. Collaborate better.</div>
        <h1 className="mx-auto mt-7 max-w-5xl text-4xl font-semibold leading-tight tracking-tight sm:text-5xl lg:text-7xl animate-[fadeInUp_.7s_ease-out_.1s_both]">Your next project starts <span className="bg-gradient-to-r from-cyan-300 via-blue-400 to-violet-400 bg-clip-text text-transparent">here.</span></h1>
        <p className="mx-auto mt-7 max-w-2xl text-base leading-7 text-gray-500 sm:text-lg animate-[fadeInUp_.7s_ease-out_.2s_both]">ProjectHub is a developer-focused platform that brings datasets, project ideas, developer profiles, and teammates together in one connected workspace.</p>
        <p className="mx-auto mt-4 max-w-2xl text-sm leading-7 text-gray-600 animate-[fadeInUp_.7s_ease-out_.3s_both]">Stop jumping between different platforms when you're ready to build. Discover the data you need, find inspiration, connect with developers who have complementary skills, and turn an idea into a real project.</p>
        <div className="mt-9 flex flex-col items-center justify-center gap-3 sm:flex-row animate-[fadeInUp_.7s_ease-out_.4s_both]">
          <Link to="/datasets" className="group inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-violet-400 to-cyan-300 px-5 py-3 text-sm font-medium text-black transition-all duration-300 hover:-translate-y-1 hover:shadow-lg hover:shadow-cyan-400/10">Explore Datasets<ArrowRight size={16} className="transition-transform duration-300 group-hover:translate-x-1"/></Link>
          <Link to="/teams" className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.02] px-5 py-3 text-sm text-gray-400 transition-all duration-300 hover:-translate-y-1 hover:border-white/20 hover:bg-white/5 hover:text-white">Find Teammates</Link>
        </div>
      </div>
    </section>

    <section className="border-y border-white/5 bg-white/[0.015] px-6 py-7 sm:px-10 lg:px-16"><div className="mx-auto grid max-w-6xl gap-4 sm:grid-cols-3"><Mini icon={<Database size={18}/>} title="Discover Data" text="Kaggle & Hugging Face"/><Mini icon={<Lightbulb size={18}/>} title="Find Ideas" text="Explore projects to build"/><Mini icon={<Users size={18}/>} title="Build Teams" text="Connect with developers"/></div></section>

    <section className="px-6 py-24 sm:px-10 lg:px-16"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-violet-300/70">Why ProjectHub</p><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">Building a project shouldn't feel like solving five different problems.</h2></div><div className="space-y-5 text-sm leading-7 text-gray-500 sm:text-base"><p>A developer can have a great project idea but struggle to find a useful dataset. Another person may have the perfect dataset but no clear idea about what to build with it.</p><p>Finding teammates can be another challenge. You might need someone comfortable with React, Python, machine learning, backend development, UI design, or another specific skill, but discovering the right person is often difficult.</p><p><span className="text-gray-300">@ProjectHub</span> brings these pieces together so that the journey from <span className="text-gray-300">idea → resources → team → project</span> becomes simpler and more connected.</p></div></div></section>

    <section className="border-y border-white/5 bg-[#0b0e14] px-6 py-24 sm:px-10 lg:px-16"><div className="mx-auto max-w-6xl"><p className="text-xs font-semibold uppercase tracking-[.2em] text-cyan-300/70">One platform</p><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">Everything around your next build.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-gray-600">ProjectHub connects the important stages of project discovery, from finding useful resources to discovering people who can help you execute an idea.</p><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">
      <Card icon={<Database size={20}/>} n="01" title="Dataset Discovery" text="Search datasets from Kaggle and Hugging Face and open the original source when you find the right one."/>
      <Card icon={<Lightbulb size={20}/>} n="02" title="Project Ideas" text="Explore project concepts across technologies and domains and turn inspiration into something you can build."/>
      <Card icon={<Users size={20}/>} n="03" title="Find Teammates" text="Search developers by names, roles, skills, locations, education and other profile information."/>
      <Card icon={<UserRound size={20}/>} n="04" title="Developer Profiles" text="Showcase skills, projects, experience, certifications, achievements, GitHub and LinkedIn."/>
      <Card icon={<Search size={20}/>} n="05" title="Smart Filtering" text="Use flexible text search and filters to quickly find the resources or people you need."/>
      <Card icon={<Rocket size={20}/>} n="06" title="Build & Collaborate" text="Bring the idea, resources and people together and move from planning toward implementation."/>
    </div></div></section>

    <section className="px-6 py-24 sm:px-10 lg:px-16"><div className="mx-auto max-w-6xl text-center"><p className="text-xs font-semibold uppercase tracking-[.2em] text-violet-300/70">The ProjectHub workflow</p><h2 className="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">Start with a thought. Finish with a project.</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-7 text-gray-600">You don't have to know everything before you begin. ProjectHub helps you discover the missing pieces as you move forward.</p><div className="mt-14 grid gap-5 md:grid-cols-4"><Step n="01" icon={<Compass size={18}/>} title="Discover" text="Find datasets, topics and project directions that interest you."/><Step n="02" icon={<Database size={18}/>} title="Choose" text="Explore resources and ideas until you find the right direction."/><Step n="03" icon={<Users size={18}/>} title="Connect" text="Find developers with the skills needed for your project."/><Step n="04" icon={<Code2 size={18}/>} title="Build" text="Bring the idea, resources and people together and create."/></div></div></section>

    <section className="border-y border-white/5 bg-white/[0.015] px-6 py-24 sm:px-10 lg:px-16"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><div className="flex h-11 w-11 items-center justify-center rounded-2xl border border-cyan-400/10 bg-cyan-400/5 text-cyan-300"><Zap size={20}/></div><h2 className="mt-6 text-3xl font-semibold tracking-tight sm:text-4xl">Built around practical learning.</h2><p className="mt-5 max-w-2xl text-sm leading-7 text-gray-500 sm:text-base">Tutorials can teach you how a technology works, but projects teach you how to use it. ProjectHub is designed around that transition.</p><p className="mt-4 max-w-2xl text-sm leading-7 text-gray-600">Use the platform to find a dataset, choose a problem, discover people with complementary skills, and work toward a complete project.</p></div><div className="grid gap-3"><Value icon={<Layers3 size={18}/>} title="Connected resources" text="Keep important parts of project discovery connected."/><Value icon={<Users size={18}/>} title="People first" text="Find teammates based on actual skills and profiles."/><Value icon={<ShieldCheck size={18}/>} title="Developer-focused" text="Designed around builders, students, learners and creators."/></div></div></section>

    <section className="px-6 py-24 sm:px-10 lg:px-16"><div className="relative mx-auto max-w-6xl overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-br from-white/[0.04] to-white/[0.015] p-8 text-center sm:p-14"><div className="pointer-events-none absolute left-1/2 top-0 h-64 w-64 -translate-x-1/2 rounded-full bg-cyan-400/10 blur-[100px]"/><div className="relative"><div className="mx-auto flex h-11 w-11 items-center justify-center rounded-2xl border border-cyan-400/10 bg-cyan-400/5 text-cyan-300"><Rocket size={20}/></div><h2 className="mt-6 text-3xl font-semibold tracking-tight sm:text-4xl">Have an idea? <span className="text-cyan-300">Start building.</span></h2><p className="mx-auto mt-5 max-w-2xl text-sm leading-7 text-gray-600">Explore datasets, discover project directions, build your developer profile, or find someone who can help you take the idea further.</p><div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row"><Link to="/datasets" className="group inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-violet-400 to-cyan-300 px-5 py-3 text-sm font-medium text-black transition-all duration-300 hover:-translate-y-1">Start Exploring<ArrowRight size={16} className="transition-transform duration-300 group-hover:translate-x-1"/></Link><Link to="/projects" className="inline-flex items-center gap-2 rounded-xl border border-white/10 bg-white/[0.02] px-5 py-3 text-sm text-gray-400 transition-all duration-300 hover:-translate-y-1 hover:border-white/20 hover:bg-white/5 hover:text-white">Browse Project Ideas</Link></div></div></div></section>

    <footer className="border-t border-white/5 bg-[#07090d] px-6 pb-10 pt-16 sm:px-10 lg:px-16"><div className="mx-auto max-w-6xl"><div className="grid gap-12 md:grid-cols-[1.3fr_.7fr_.7fr]"><div><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-violet-400 to-cyan-300 text-black"><Code2 size={19}/></div><div><p className="text-base font-semibold text-gray-200">ProjectHub</p><p className="text-xs text-gray-600">@ProjectHub</p></div></div><p className="mt-5 max-w-md text-sm leading-7 text-gray-600">A developer-focused platform for discovering datasets, exploring project ideas, finding teammates, and turning ideas into real-world projects.</p><p className="mt-4 text-xs leading-6 text-gray-700">Built to make project discovery and collaboration simpler, more connected and more accessible.</p></div><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-gray-500">Platform</p><div className="mt-5 flex flex-col gap-3"><FooterLink to="/datasets" label="Datasets"/><FooterLink to="/projects" label="Project Ideas"/><FooterLink to="/teams" label="Find Teammates"/><FooterLink to="/about" label="About ProjectHub"/></div></div><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-gray-500">Contact</p><div className="mt-5 flex flex-col gap-3"><a href="mailto:sivabadeti2005@gmail.com" className="flex items-center gap-3 text-sm text-gray-600 transition-all duration-300 hover:translate-x-1 hover:text-gray-300"><Mail size={15}/>sivabadeti2005@gmail.com</a><a href="tel:+917013419797" className="flex items-center gap-3 text-sm text-gray-600 transition-all duration-300 hover:translate-x-1 hover:text-gray-300"><Phone size={15}/>+91 7013419797</a><a href="https://github.com/" target="_blank" rel="noopener noreferrer" className="group flex items-center gap-3 text-sm text-gray-600 transition-all duration-300 hover:translate-x-1 hover:text-white"><FaGithub
                      size={17}
                      className="transition-transform duration-300 group-hover:scale-110"
                    />GitHub<ChevronRight size={13} className="transition-transform duration-300 group-hover:translate-x-1"/></a></div></div></div><div className="mt-14 flex flex-col gap-3 border-t border-white/5 pt-6 text-xs text-gray-700 sm:flex-row sm:items-center sm:justify-between"><p>© {new Date().getFullYear()} ProjectHub. Built with curiosity and collaboration.</p><p>@ProjectHub</p></div></div></footer>

    <style>{`@keyframes fadeInUp{from{opacity:0;transform:translateY(18px)}to{opacity:1;transform:translateY(0)}}@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important;scroll-behavior:auto!important}}`}</style>
  </div>
);

const Card=({icon,n,title,text})=><div className="group rounded-2xl border border-white/10 bg-white/[0.02] p-6 transition-all duration-300 ease-out hover:-translate-y-1 hover:border-white/20 hover:bg-white/[0.035] hover:shadow-xl hover:shadow-black/20"><div className="flex items-start justify-between"><div className="flex h-10 w-10 items-center justify-center rounded-xl border border-cyan-400/10 bg-cyan-400/5 text-cyan-300 transition-all duration-300 group-hover:scale-110 group-hover:bg-cyan-400/10">{icon}</div><span className="text-xs font-medium text-gray-700">{n}</span></div><h3 className="mt-6 text-base font-semibold text-gray-200">{title}</h3><p className="mt-3 text-sm leading-6 text-gray-600">{text}</p></div>;
const Step=({n,icon,title,text})=><div className="group rounded-2xl border border-white/10 bg-white/[0.02] p-6 transition-all duration-300 hover:-translate-y-1 hover:border-cyan-400/15 hover:bg-white/[0.035]"><div className="flex items-center justify-between"><span className="text-xs font-semibold tracking-wider text-cyan-300/60">{n}</span><span className="text-gray-700 transition-all duration-300 group-hover:scale-110 group-hover:text-cyan-300">{icon}</span></div><h3 className="mt-5 text-base font-semibold text-gray-200">{title}</h3><p className="mt-3 text-sm leading-6 text-gray-600">{text}</p></div>;
const Mini=({icon,title,text})=><div className="group flex items-center gap-4 rounded-2xl border border-white/10 bg-white/[0.02] p-4 transition-all duration-300 hover:-translate-y-0.5 hover:border-white/15 hover:bg-white/[0.035]"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white/5 text-gray-500 transition-all duration-300 group-hover:scale-105 group-hover:text-cyan-300">{icon}</div><div><p className="text-sm font-medium text-gray-300">{title}</p><p className="mt-1 text-xs text-gray-600">{text}</p></div></div>;
const Value=({icon,title,text})=><div className="group flex gap-4 rounded-2xl border border-white/10 bg-black/10 p-4 transition-all duration-300 hover:border-white/15 hover:bg-white/[0.025]"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white/5 text-gray-400 transition-all duration-300 group-hover:scale-105 group-hover:text-cyan-300">{icon}</div><div><h3 className="text-sm font-medium text-gray-300">{title}</h3><p className="mt-1.5 text-xs leading-5 text-gray-600">{text}</p></div></div>;
const FooterLink=({to,label})=><Link to={to} className="group flex items-center gap-2 text-sm text-gray-600 transition-all duration-300 hover:translate-x-1 hover:text-gray-300">{label}<ChevronRight size={13} className="opacity-0 transition-all duration-300 group-hover:translate-x-1 group-hover:opacity-100"/></Link>;

export default Home;